//e2e 共用設施之單一引用點: 指向 w-package-tools-e2e(devDependency, 規格見其 README).
//2026-09-29 起由姊妹專案 w-web-sso 之 srcPack 改指套件 1.0.2(srcPack 已移入該套件並刪除); 套件依賴(sharp、pixelmatch、pngjs、playwright)自本專案 node_modules 解析.
//2026-09-30 升 1.0.3: 新增 probeStuckTooltip(原四專案各自手寫於 e2e-setup 之同一實作收斂至套件)、gridContentBox 空表訊息外擴、runIsolatedE2e 之 targets.
//共用層、harness 與測試檔一律自本檔 import, 不直接引用套件路徑.
//本專案之 harness 所有權政策(own: 只用自建、port 被佔即拋錯、跨行程互斥)不在套件內, 仍由 ./harnessLifecycle.mjs 提供.
export { default as assertBaselineMatch } from 'w-package-tools-e2e/src/assertBaselineMatch.mjs'
export { default as assertTextSpec } from 'w-package-tools-e2e/src/assertTextSpec.mjs'
export { default as canvasInkRects } from 'w-package-tools-e2e/src/canvasInkRects.mjs'
export { default as captureStable } from 'w-package-tools-e2e/src/captureStable.mjs'
export { default as captureStableWithBox } from 'w-package-tools-e2e/src/captureStableWithBox.mjs'
export { default as chromiumLaunchArgs } from 'w-package-tools-e2e/src/chromiumLaunchArgs.mjs'
export { default as collectDomText } from 'w-package-tools-e2e/src/collectDomText.mjs'
export { default as compareImageDirs } from 'w-package-tools-e2e/src/compareImageDirs.mjs'
export { default as composeBox } from 'w-package-tools-e2e/src/composeBox.mjs'
export { default as createBaselineGate } from 'w-package-tools-e2e/src/createBaselineGate.mjs'
export { default as createKnownDefect } from 'w-package-tools-e2e/src/createKnownDefect.mjs'
export { default as createServiceManager } from 'w-package-tools-e2e/src/createServiceManager.mjs'
export { default as createTempSettings } from 'w-package-tools-e2e/src/createTempSettings.mjs'
export { default as cropRegion } from 'w-package-tools-e2e/src/cropRegion.mjs'
export { default as diffBaselineSnapshots } from 'w-package-tools-e2e/src/diffBaselineSnapshots.mjs'
export { default as findOrphanBaselines } from 'w-package-tools-e2e/src/findOrphanBaselines.mjs'
export { default as getE2eMode } from 'w-package-tools-e2e/src/getE2eMode.mjs'
export { default as gridContentBox } from 'w-package-tools-e2e/src/gridContentBox.mjs'
export { default as inkRect, INK_PAD } from 'w-package-tools-e2e/src/inkRect.mjs'
export { default as isChildAlive } from 'w-package-tools-e2e/src/isChildAlive.mjs'
export { default as itemsUnionBox } from 'w-package-tools-e2e/src/itemsUnionBox.mjs'
export { default as killOwnTree } from 'w-package-tools-e2e/src/killOwnTree.mjs'
export { default as killPortListeners } from 'w-package-tools-e2e/src/killPortListeners.mjs'
export { default as launchBrowser } from 'w-package-tools-e2e/src/launchBrowser.mjs'
export { default as listenerPids } from 'w-package-tools-e2e/src/listenerPids.mjs'
export { default as maskRegions } from 'w-package-tools-e2e/src/maskRegions.mjs'
export { default as normalizeShots } from 'w-package-tools-e2e/src/normalizeShots.mjs'
export { default as openCasePage } from 'w-package-tools-e2e/src/openCasePage.mjs'
export { default as overlayImageAt } from 'w-package-tools-e2e/src/overlayImageAt.mjs'
export { default as overlayRegions } from 'w-package-tools-e2e/src/overlayRegions.mjs'
export { default as pageHasText } from 'w-package-tools-e2e/src/pageHasText.mjs'
export { default as parseListenerPids } from 'w-package-tools-e2e/src/parseListenerPids.mjs'
export { default as pidExists } from 'w-package-tools-e2e/src/pidExists.mjs'
export { default as pollUntil } from 'w-package-tools-e2e/src/pollUntil.mjs'
export { default as probeHttp } from 'w-package-tools-e2e/src/probeHttp.mjs'
export { default as probeStuckTooltip } from 'w-package-tools-e2e/src/probeStuckTooltip.mjs'
export { default as registerCleanupHooks } from 'w-package-tools-e2e/src/registerCleanupHooks.mjs'
export { default as resetAgGridScroll } from 'w-package-tools-e2e/src/resetAgGridScroll.mjs'
export { default as rowBoxSel } from 'w-package-tools-e2e/src/rowBoxSel.mjs'
export { default as runBaselineCase } from 'w-package-tools-e2e/src/runBaselineCase.mjs'
export { default as runIsolatedE2e } from 'w-package-tools-e2e/src/runIsolatedE2e.mjs'
export { default as sleepSync } from 'w-package-tools-e2e/src/sleepSync.mjs'
export { default as snapshotBaselines } from 'w-package-tools-e2e/src/snapshotBaselines.mjs'
export { default as stepShots } from 'w-package-tools-e2e/src/stepShots.mjs'
export { default as typeIntoInput } from 'w-package-tools-e2e/src/typeIntoInput.mjs'
export { default as typeIntoNthInput } from 'w-package-tools-e2e/src/typeIntoNthInput.mjs'
export { default as waitAlertGone } from 'w-package-tools-e2e/src/waitAlertGone.mjs'
export { default as waitChildExit } from 'w-package-tools-e2e/src/waitChildExit.mjs'
export { default as waitColResizeOverlay } from 'w-package-tools-e2e/src/waitColResizeOverlay.mjs'
export { default as waitDrawerReady } from 'w-package-tools-e2e/src/waitDrawerReady.mjs'
export { default as waitGridIdle } from 'w-package-tools-e2e/src/waitGridIdle.mjs'
export { default as waitUntilExist } from 'w-package-tools-e2e/src/waitUntilExist.mjs'
